package io.github.guisso.javasepersistencewithhibernateorm.beta.material.gui;

import io.github.guisso.javasepersistencewithhibernateorm.beta.material.Material;
import io.github.guisso.javasepersistencewithhibernateorm.beta.material.MaterialRepository;
import java.util.List;
import javax.swing.JOptionPane;

/**
 * @author stefo
 */

public class ExibirMaterial extends javax.swing.JFrame {

    private MaterialRepository materialRepository;
    private MaterialTableModel ativasTableModel;
    private MaterialTableModel lixeiraTableModel;
    private Material materialSelecionado;
    
    public ExibirMaterial() {
        initComponents();
        inicializarComponentesLogicos();
    }

    private void inicializarComponentesLogicos() {
        this.materialRepository = new MaterialRepository();
        this.ativasTableModel = new MaterialTableModel();
        this.jTable1.setModel(ativasTableModel); // Usa jTable1
        this.lixeiraTableModel = new MaterialTableModel();
        this.jTable2.setModel(lixeiraTableModel); // Usa jTable2
        carregarTabelas();
        adicionarListenerSelecaoTabela();
    }

    private void carregarTabelas() {
        List<Material> ativos = materialRepository.findAllActive();
        ativasTableModel.setMateriais(ativos);
        List<Material> excluidos = materialRepository.findAllInTrash();
        lixeiraTableModel.setMateriais(excluidos);
    }

    private void adicionarListenerSelecaoTabela() {
        jTable1.getSelectionModel().addListSelectionListener(event -> {
            if (!event.getValueIsAdjusting() && jTable1.getSelectedRow() != -1) {
                int modelRow = jTable1.convertRowIndexToModel(jTable1.getSelectedRow());
                materialSelecionado = ativasTableModel.getMaterialEm(modelRow);
                preencherFormulario(materialSelecionado);
            }
        });
    }

    private void preencherFormulario(Material material) {
        if (material != null) {
            txt_Nome.setText(material.getNome());
            txt_Tipo.setText(material.getTipo());
            txt_Quantidade.setText(String.valueOf(material.getQuantidadeEmEstoque()));
            txt_Unidade.setText(material.getUnidade());
            txt_NivelMinimo.setText(String.valueOf(material.getNivelMinimo()));
            chk_Ativo.setSelected(material.getAtivo() != null && material.getAtivo());
        }
    }

    private void limparFormulario() {
        materialSelecionado = null;
        txt_Nome.setText("");
        txt_Tipo.setText("");
        txt_Quantidade.setText("");
        txt_Unidade.setText("");
        txt_NivelMinimo.setText("");
        chk_Ativo.setSelected(false);
        jTable1.clearSelection();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cadastro_pnl = new javax.swing.JPanel();
        lbl_Nome = new javax.swing.JLabel();
        lbl_Tipo = new javax.swing.JLabel();
        lbl_Quantidade = new javax.swing.JLabel();
        lbl_Unidade = new javax.swing.JLabel();
        lbl_NivelMinimo = new javax.swing.JLabel();
        txt_NivelMinimo = new javax.swing.JTextField();
        txt_Unidade = new javax.swing.JTextField();
        txt_Quantidade = new javax.swing.JTextField();
        txt_Tipo = new javax.swing.JTextField();
        txt_Nome = new javax.swing.JTextField();
        chk_Ativo = new javax.swing.JCheckBox();
        btn_Salvar = new javax.swing.JButton();
        btn_Buscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Listagem_pnl = new javax.swing.JPanel();
        Lixeira_pnl = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_Deletar = new javax.swing.JButton();
        btn_Alterar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btn_DeletarPermanente = new javax.swing.JButton();
        btn_Restaurar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Cadastro_pnl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_Nome.setText("Nome:");

        lbl_Tipo.setText("Tipo:");

        lbl_Quantidade.setText("Estoque:");

        lbl_Unidade.setText("Unidade:");

        lbl_NivelMinimo.setText("Nível Mínimo:");

        chk_Ativo.setText("Ativo");

        btn_Salvar.setText("Salvar");
        btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarActionPerformed(evt);
            }
        });

        btn_Buscar.setText("Buscar");
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Cadastro_pnlLayout = new javax.swing.GroupLayout(Cadastro_pnl);
        Cadastro_pnl.setLayout(Cadastro_pnlLayout);
        Cadastro_pnlLayout.setHorizontalGroup(
            Cadastro_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cadastro_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Cadastro_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Cadastro_pnlLayout.createSequentialGroup()
                        .addGroup(Cadastro_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Cadastro_pnlLayout.createSequentialGroup()
                                .addComponent(lbl_Nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Nome))
                            .addGroup(Cadastro_pnlLayout.createSequentialGroup()
                                .addComponent(lbl_NivelMinimo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_NivelMinimo, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))
                            .addGroup(Cadastro_pnlLayout.createSequentialGroup()
                                .addGroup(Cadastro_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_Unidade)
                                    .addComponent(lbl_Quantidade))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Cadastro_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Quantidade)
                                    .addComponent(txt_Unidade)))
                            .addGroup(Cadastro_pnlLayout.createSequentialGroup()
                                .addComponent(lbl_Tipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Tipo)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Cadastro_pnlLayout.createSequentialGroup()
                        .addComponent(chk_Ativo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Salvar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Cadastro_pnlLayout.setVerticalGroup(
            Cadastro_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cadastro_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Cadastro_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Nome)
                    .addComponent(txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Cadastro_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Tipo)
                    .addComponent(txt_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Cadastro_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Quantidade)
                    .addComponent(txt_Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Cadastro_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Unidade)
                    .addComponent(txt_Unidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Cadastro_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_NivelMinimo)
                    .addComponent(txt_NivelMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Cadastro_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chk_Ativo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Cadastro_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_Salvar)
                        .addComponent(btn_Buscar)))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Material");

        Listagem_pnl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btn_Deletar.setText("Deletar");
        btn_Deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeletarActionPerformed(evt);
            }
        });

        btn_Alterar.setText("Alterar");
        btn_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 163, Short.MAX_VALUE)
                        .addComponent(btn_Alterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Deletar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Deletar)
                    .addComponent(btn_Alterar)))
        );

        Lixeira_pnl.addTab("Ativos", jPanel1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        btn_DeletarPermanente.setText("Deletar Permanentemente");
        btn_DeletarPermanente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeletarPermanenteActionPerformed(evt);
            }
        });

        btn_Restaurar.setText("Restaurar");
        btn_Restaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RestaurarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(btn_Restaurar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_DeletarPermanente)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_DeletarPermanente)
                    .addComponent(btn_Restaurar)))
        );

        Lixeira_pnl.addTab("Lixeira", jPanel2);

        javax.swing.GroupLayout Listagem_pnlLayout = new javax.swing.GroupLayout(Listagem_pnl);
        Listagem_pnl.setLayout(Listagem_pnlLayout);
        Listagem_pnlLayout.setHorizontalGroup(
            Listagem_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Listagem_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lixeira_pnl)
                .addContainerGap())
        );
        Listagem_pnlLayout.setVerticalGroup(
            Listagem_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Listagem_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lixeira_pnl)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Cadastro_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Listagem_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Cadastro_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Listagem_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RestaurarActionPerformed
        int[] selectedRows = jTable2.getSelectedRows();
        if (selectedRows.length == 0) {
            JOptionPane.showMessageDialog(this, "Selecione um ou mais materiais para restaurar.");
            return;
        }

        int resposta = JOptionPane.showConfirmDialog(this, "Deseja restaurar " + selectedRows.length + " material(s)?", "Confirmação", JOptionPane.YES_NO_OPTION);

        if (resposta == JOptionPane.YES_OPTION) {
            for (int viewRow : selectedRows) {
                int modelRow = jTable2.convertRowIndexToModel(viewRow);
                Long id = (Long) lixeiraTableModel.getValueAt(modelRow, 0);
                materialRepository.restore(id); // Restaura o item (muda ativo para true)
            }
            carregarTabelas();
        }
    }//GEN-LAST:event_btn_RestaurarActionPerformed

    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed
        String nomeBusca = txt_Nome.getText().trim();
        if (!nomeBusca.isEmpty()) {
            // Se houver texto, busca pelo nome
            List<Material> resultados = materialRepository.findByNome(nomeBusca);
            ativasTableModel.setMateriais(resultados);
        } else {
            // Se o campo de busca estiver vazio, recarrega todos os materiais ativos
            carregarTabelas();
        }
    }//GEN-LAST:event_btn_BuscarActionPerformed

    private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed
        try {
            // Se nenhum material estiver selecionado, cria um novo. Senão, usa o selecionado para atualizar.
            Material material = (materialSelecionado == null) ? new Material() : materialSelecionado;

            // Pega os dados dos campos de texto e atribui ao objeto
            material.setNome(txt_Nome.getText());
            material.setTipo(txt_Tipo.getText());
            material.setQuantidadeEmEstoque(Double.parseDouble(txt_Quantidade.getText()));
            material.setUnidade(txt_Unidade.getText());
            material.setNivelMinimo(Double.parseDouble(txt_NivelMinimo.getText()));
            material.setAtivo(chk_Ativo.isSelected());

            // Salva ou atualiza no banco de dados
            materialRepository.saveOrUpdate(material);

            JOptionPane.showMessageDialog(this, "Material salvo com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            // Limpa o formulário e recarrega as tabelas para exibir a informação atualizada
            limparFormulario();
            carregarTabelas();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Os campos 'Estoque' e 'Nível Mínimo' devem ser números válidos.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Erro de Validação: " + e.getMessage(), "Dados Inválidos", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro ao salvar o material: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_SalvarActionPerformed

    private void btn_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AlterarActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione um material na tabela para alterar.");
            return;
        }

        // A seleção na tabela já chama o preencherFormulario, mas este botão
        // garante que o item correto seja carregado para edição.
        int modelRow = jTable1.convertRowIndexToModel(selectedRow);
        materialSelecionado = ativasTableModel.getMaterialEm(modelRow);
        preencherFormulario(materialSelecionado);
    }//GEN-LAST:event_btn_AlterarActionPerformed

    private void btn_DeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeletarActionPerformed
        int[] selectedRows = jTable1.getSelectedRows();
        if (selectedRows.length == 0) {
            JOptionPane.showMessageDialog(this, "Selecione um ou mais materiais para mover para a lixeira.");
            return;
        }

        int resposta = JOptionPane.showConfirmDialog(this, "Deseja mover " + selectedRows.length + " material(s) para a lixeira?", "Confirmação", JOptionPane.YES_NO_OPTION);

        if (resposta == JOptionPane.YES_OPTION) {
            for (int viewRow : selectedRows) {
                int modelRow = jTable1.convertRowIndexToModel(viewRow);
                // Pega o ID da coluna 0 (a primeira coluna) do item selecionado
                Long id = (Long) ativasTableModel.getValueAt(modelRow, 0);
                materialRepository.softDelete(id); // Move para a lixeira (muda ativo para false)
            }
            carregarTabelas();
            limparFormulario();
        }
    }//GEN-LAST:event_btn_DeletarActionPerformed

    private void btn_DeletarPermanenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeletarPermanenteActionPerformed
        int[] selectedRows = jTable2.getSelectedRows();
        if (selectedRows.length == 0) {
            JOptionPane.showMessageDialog(this, "Selecione um ou mais itens para excluir permanentemente.");
            return;
        }

        int resposta = JOptionPane.showConfirmDialog(this, 
            "Excluir permanentemente " + selectedRows.length + " material(s)?\n\nESSA AÇÃO NÃO PODE SER DESFEITA.", 
            "Atenção!", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.WARNING_MESSAGE);

        if (resposta == JOptionPane.YES_OPTION) {
            for (int viewRow : selectedRows) {
                int modelRow = jTable2.convertRowIndexToModel(viewRow);
                Long id = (Long) lixeiraTableModel.getValueAt(modelRow, 0);
                materialRepository.hardDelete(id); // Deleta do banco de dados para sempre
            }
            carregarTabelas();
        }
    }//GEN-LAST:event_btn_DeletarPermanenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExibirMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExibirMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExibirMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExibirMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExibirMaterial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cadastro_pnl;
    private javax.swing.JPanel Listagem_pnl;
    private javax.swing.JTabbedPane Lixeira_pnl;
    private javax.swing.JButton btn_Alterar;
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_Deletar;
    private javax.swing.JButton btn_DeletarPermanente;
    private javax.swing.JButton btn_Restaurar;
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JCheckBox chk_Ativo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbl_NivelMinimo;
    private javax.swing.JLabel lbl_Nome;
    private javax.swing.JLabel lbl_Quantidade;
    private javax.swing.JLabel lbl_Tipo;
    private javax.swing.JLabel lbl_Unidade;
    private javax.swing.JTextField txt_NivelMinimo;
    private javax.swing.JTextField txt_Nome;
    private javax.swing.JTextField txt_Quantidade;
    private javax.swing.JTextField txt_Tipo;
    private javax.swing.JTextField txt_Unidade;
    // End of variables declaration//GEN-END:variables
}
