package io.github.guisso.javasepersistencewithhibernateorm.beta.categoria.gui;

import io.github.guisso.javasepersistencewithhibernateorm.beta.categoria.Categoria;
import io.github.guisso.javasepersistencewithhibernateorm.beta.categoria.CategoriaRepository;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author stefo
 */

public class ExibirCategoria extends javax.swing.JFrame {

    private CategoriaRepository categoriaRepository;
    private CategoriaTableModel ativasTableModel;
    private CategoriaTableModel lixeiraTableModel;
    private Categoria categoriaSelecionada;
    
    public ExibirCategoria() {
        initComponents();
        inicializarComponentesLogicos();
    }

    private void inicializarComponentesLogicos() {
        this.categoriaRepository = new CategoriaRepository();
        this.ativasTableModel = new CategoriaTableModel();
        this.jTable1.setModel(ativasTableModel);
        this.lixeiraTableModel = new CategoriaTableModel();
        this.jTable2.setModel(lixeiraTableModel);
        carregarTabelas();
        adicionarListenerSelecaoTabela();
    }

    private void carregarTabelas() {
        List<Categoria> ativas = categoriaRepository.findAllActive();
        ativasTableModel.setCategorias(ativas);
        List<Categoria> excluidas = categoriaRepository.findAllInTrash();
        lixeiraTableModel.setCategorias(excluidas);
    }

    private void adicionarListenerSelecaoTabela() {
        jTable1.getSelectionModel().addListSelectionListener(event -> {
            if (!event.getValueIsAdjusting() && jTable1.getSelectedRow() != -1) {
                int modelRow = jTable1.convertRowIndexToModel(jTable1.getSelectedRow());
                categoriaSelecionada = ativasTableModel.getCategoriaEm(modelRow);
                preencherFormulario(categoriaSelecionada);
            }
        });
    }

    private void preencherFormulario(Categoria categoria) {
        if (categoria != null) {
            txt_Nome.setText(categoria.getNome());
            txt_Descricao.setText(categoria.getDescricao());
            chk_Ativo.setSelected(categoria.getAtivo() != null && categoria.getAtivo());
        }
    }

    private void limparFormulario() {
        categoriaSelecionada = null;
        txt_Nome.setText("");
        txt_Descricao.setText("");
        chk_Ativo.setSelected(true);
        jTable1.clearSelection();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Cadastro_pnl = new javax.swing.JPanel();
        lbl_Nome = new javax.swing.JLabel();
        txt_Nome = new javax.swing.JTextField();
        lbl_Descricao = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_Descricao = new javax.swing.JTextArea();
        chk_Ativo = new javax.swing.JCheckBox();
        btn_Salvar = new javax.swing.JButton();
        btn_Buscar = new javax.swing.JButton();
        Listagem_pnl = new javax.swing.JPanel();
        Lixeira_pnl = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_Deletar = new javax.swing.JButton();
        btn_Alterar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btn_DeletarPermanente = new javax.swing.JButton();
        btn_Restaurar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Categoria");

        Cadastro_pnl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_Nome.setText("Nome:");

        txt_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NomeActionPerformed(evt);
            }
        });

        lbl_Descricao.setText("Descrição:");

        txt_Descricao.setColumns(20);
        txt_Descricao.setRows(5);
        jScrollPane3.setViewportView(txt_Descricao);

        chk_Ativo.setText("Ativo");

        btn_Salvar.setText("Salvar");
        btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarActionPerformed(evt);
            }
        });

        btn_Buscar.setText("Buscar");
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Cadastro_pnlLayout = new javax.swing.GroupLayout(Cadastro_pnl);
        Cadastro_pnl.setLayout(Cadastro_pnlLayout);
        Cadastro_pnlLayout.setHorizontalGroup(
            Cadastro_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cadastro_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Cadastro_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Cadastro_pnlLayout.createSequentialGroup()
                        .addComponent(lbl_Descricao)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Cadastro_pnlLayout.createSequentialGroup()
                        .addGroup(Cadastro_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                            .addGroup(Cadastro_pnlLayout.createSequentialGroup()
                                .addComponent(lbl_Nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Nome))
                            .addGroup(Cadastro_pnlLayout.createSequentialGroup()
                                .addComponent(chk_Ativo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Buscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Salvar)))
                        .addContainerGap())))
        );
        Cadastro_pnlLayout.setVerticalGroup(
            Cadastro_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cadastro_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Cadastro_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Nome)
                    .addComponent(txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Cadastro_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Cadastro_pnlLayout.createSequentialGroup()
                        .addComponent(lbl_Descricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chk_Ativo))
                    .addGroup(Cadastro_pnlLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(Cadastro_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Salvar)
                            .addComponent(btn_Buscar))))
                .addContainerGap())
        );

        Listagem_pnl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btn_Deletar.setText("Deletar");
        btn_Deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeletarActionPerformed(evt);
            }
        });

        btn_Alterar.setText("Alterar");
        btn_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 214, Short.MAX_VALUE)
                .addComponent(btn_Alterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Deletar))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Deletar)
                    .addComponent(btn_Alterar)))
        );

        Lixeira_pnl.addTab("Ativos", jPanel1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        btn_DeletarPermanente.setText("Deletar Permanentemente");
        btn_DeletarPermanente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeletarPermanenteActionPerformed(evt);
            }
        });

        btn_Restaurar.setText("Restaurar");
        btn_Restaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RestaurarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 105, Short.MAX_VALUE)
                        .addComponent(btn_Restaurar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_DeletarPermanente))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_DeletarPermanente)
                    .addComponent(btn_Restaurar)))
        );

        Lixeira_pnl.addTab("Lixeira", jPanel2);

        javax.swing.GroupLayout Listagem_pnlLayout = new javax.swing.GroupLayout(Listagem_pnl);
        Listagem_pnl.setLayout(Listagem_pnlLayout);
        Listagem_pnlLayout.setHorizontalGroup(
            Listagem_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Listagem_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lixeira_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addContainerGap())
        );
        Listagem_pnlLayout.setVerticalGroup(
            Listagem_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Listagem_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lixeira_pnl)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Cadastro_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Listagem_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cadastro_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Listagem_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NomeActionPerformed

    private void btn_RestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RestaurarActionPerformed
        int[] selectedRows = jTable2.getSelectedRows();
        if (selectedRows.length == 0) {
            JOptionPane.showMessageDialog(this, "Selecione uma ou mais categorias para restaurar.");
            return;
        }
        int resposta = JOptionPane.showConfirmDialog(this, "Restaurar " + selectedRows.length + " categoria(s)?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            for (int row : selectedRows) {
                int modelRow = jTable2.convertRowIndexToModel(row);
                Long id = (Long) lixeiraTableModel.getValueAt(modelRow, 0);
                categoriaRepository.restore(id);
            }
            carregarTabelas();
        }
    }//GEN-LAST:event_btn_RestaurarActionPerformed

    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed
        String nomeBusca = txt_Nome.getText().trim();
        if (!nomeBusca.isEmpty()) {
            List<Categoria> resultados = categoriaRepository.findByNome(nomeBusca);
            ativasTableModel.setCategorias(resultados);
        } else {
            carregarTabelas();
        }
    }//GEN-LAST:event_btn_BuscarActionPerformed

    private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed
        try {
            Categoria categoria = (categoriaSelecionada == null) ? new Categoria() : categoriaSelecionada;
            categoria.setNome(txt_Nome.getText());
            categoria.setDescricao(txt_Descricao.getText());
            categoria.setAtivo(chk_Ativo.isSelected());
            categoriaRepository.saveOrUpdate(categoria); // Ou saveOrUpdate, se for o caso
            JOptionPane.showMessageDialog(this, "Categoria salva com sucesso!");
            limparFormulario();
            carregarTabelas();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar categoria: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_SalvarActionPerformed

    private void btn_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AlterarActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma categoria para alterar.");
            return;
        }
        int modelRow = jTable1.convertRowIndexToModel(selectedRow);
        categoriaSelecionada = ativasTableModel.getCategoriaEm(modelRow);
        preencherFormulario(categoriaSelecionada);
    }//GEN-LAST:event_btn_AlterarActionPerformed

    private void btn_DeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeletarActionPerformed
        int[] selectedRows = jTable1.getSelectedRows();
        if (selectedRows.length == 0) {
            JOptionPane.showMessageDialog(this, "Selecione uma ou mais categorias para mover para a lixeira.");
            return;
        }
        int resposta = JOptionPane.showConfirmDialog(this, "Mover " + selectedRows.length + " categoria(s) para a lixeira?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            for (int row : selectedRows) {
                int modelRow = jTable1.convertRowIndexToModel(row);
                Long id = (Long) ativasTableModel.getValueAt(modelRow, 0);
                categoriaRepository.softDelete(id);
            }
            carregarTabelas();
            limparFormulario();
        }
    }//GEN-LAST:event_btn_DeletarActionPerformed

    private void btn_DeletarPermanenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeletarPermanenteActionPerformed
        int[] selectedRows = jTable2.getSelectedRows();
        if (selectedRows.length == 0) {
            JOptionPane.showMessageDialog(this, "Selecione um ou mais itens para excluir permanentemente.");
            return;
        }
        int resposta = JOptionPane.showConfirmDialog(this, "Excluir permanentemente " + selectedRows.length + " categoria(s)?\nESSA AÇÃO NÃO PODE SER DESFEITA.", "Atenção!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (resposta == JOptionPane.YES_OPTION) {
            for (int row : selectedRows) {
                int modelRow = jTable2.convertRowIndexToModel(row);
                Long id = (Long) lixeiraTableModel.getValueAt(modelRow, 0);
                categoriaRepository.hardDelete(id);
            }
            carregarTabelas();
        }
    }//GEN-LAST:event_btn_DeletarPermanenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExibirCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExibirCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExibirCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExibirCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExibirCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cadastro_pnl;
    private javax.swing.JPanel Listagem_pnl;
    private javax.swing.JTabbedPane Lixeira_pnl;
    private javax.swing.JButton btn_Alterar;
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_Deletar;
    private javax.swing.JButton btn_DeletarPermanente;
    private javax.swing.JButton btn_Restaurar;
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JCheckBox chk_Ativo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbl_Descricao;
    private javax.swing.JLabel lbl_Nome;
    private javax.swing.JTextArea txt_Descricao;
    private javax.swing.JTextField txt_Nome;
    // End of variables declaration//GEN-END:variables
}
