/*
 * Copyright (C) 2025 felip
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package io.github.guisso.javasepersistencewithhibernateorm.beta.compra.gui;

import io.github.guisso.javasepersistencewithhibernateorm.beta.compra.Compra;
import io.github.guisso.javasepersistencewithhibernateorm.beta.compra.CompraRepository;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.JLabel;
import java.util.Optional;

/**
 *
 * @author felip
 */
public class exibirCompras extends javax.swing.JFrame {

    private CompraRepository compraRepository;
    private CompraTableModel ativosTableModel;
    private CompraTableModel lixeiraTableModel;
    private Compra compraSelecionado;

    public exibirCompras() {
        initComponents();
        this.compraRepository = new CompraRepository();
        this.ativosTableModel = new CompraTableModel();
        this.tblAtivos.setModel(ativosTableModel);
        this.lixeiraTableModel = new CompraTableModel();
        this.tblLixeira.setModel(lixeiraTableModel);
        carregarTabelas();
    }

    private void carregarTabelas() {

        List<Compra> ativos = compraRepository.findAllActive();
        ativosTableModel.setCompras(ativos);

        List<Compra> excluidos = compraRepository.findAllInTrash();
        lixeiraTableModel.setCompras(excluidos);
    }

    private void limparFormulario() {
        txtUsuario.setText("");
        txtFornecedor.setText("");
        txtItens.setText("");
        txtDataCompra.setText("");
        txtValorTotal.setText("");
        txtNotaFiscal.setText("");

        tblAtivos.clearSelection();

        this.compraSelecionado = null;
    }

    private void preencherFormulario(Compra compra) {
        if (compra == null) {
            return;
        }

        DateTimeFormatter formatador = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        txtUsuario.setText(compra.getUsuario());
        txtFornecedor.setText(compra.getFornecedor());
        txtItens.setText(compra.getItens());
        txtDataCompra.setText(compra.getDataCompra().format(formatador));
        txtValorTotal.setText(String.valueOf(compra.getValorTotal()).replace('.', ','));
        txtNotaFiscal.setText(compra.getNumeroNotaFiscal());
    }

    private void exibirAvisoTemporario(String mensagem, JLabel labelDeAviso) {
        labelDeAviso.setText(mensagem);

        Timer timer = new Timer(3000, e -> {
            labelDeAviso.setText("");
        });

        timer.setRepeats(false);
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtFornecedor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtItens = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDataCompra = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNotaFiscal = new javax.swing.JTextField();
        bntSalvar = new javax.swing.JButton();
        lbFormulario = new javax.swing.JLabel();
        btnBusca = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAtivos = new javax.swing.JTable();
        bntDeletar = new javax.swing.JButton();
        bntAlterar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLixeira = new javax.swing.JTable();
        bntDeletarBanco = new javax.swing.JButton();
        bntRestaurar = new javax.swing.JButton();
        lbAviso = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setText("Usuario");

        jLabel8.setText("Fornecedor");

        jLabel9.setText("Itens");

        jLabel10.setText("Data de Compra");

        jLabel11.setText("Valor da Compra");

        jLabel12.setText("Número da Nota Fiscal");

        bntSalvar.setText("Salvar");
        bntSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvarActionPerformed(evt);
            }
        });

        lbFormulario.setForeground(new java.awt.Color(255, 0, 0));

        btnBusca.setText("Busca");
        btnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsuario)
                    .addComponent(txtFornecedor)
                    .addComponent(txtItens)
                    .addComponent(txtDataCompra)
                    .addComponent(txtValorTotal)
                    .addComponent(txtNotaFiscal)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(0, 285, Short.MAX_VALUE))
                    .addComponent(lbFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bntSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBusca)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntSalvar)
                    .addComponent(btnBusca))
                .addContainerGap())
        );

        tblAtivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAtivos);

        bntDeletar.setText("Deletar");
        bntDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDeletarActionPerformed(evt);
            }
        });

        bntAlterar.setText("Alterar");
        bntAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bntAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntDeletar)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntDeletar)
                    .addComponent(bntAlterar))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ativo", jPanel3);

        tblLixeira.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblLixeira);

        bntDeletarBanco.setText("Deletar");
        bntDeletarBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDeletarBancoActionPerformed(evt);
            }
        });

        bntRestaurar.setText("Restaurar");
        bntRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRestaurarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bntRestaurar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntDeletarBanco)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntRestaurar)
                    .addComponent(bntDeletarBanco))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Lixeira", jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        lbAviso.setForeground(new java.awt.Color(255, 204, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("PAINEL DE COMPRA");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lbAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarActionPerformed
        try {
            lbFormulario.setText("");

            String usuario = txtUsuario.getText();
            String fornecedor = txtFornecedor.getText();
            String itens = txtItens.getText();
            String dataTexto = txtDataCompra.getText();
            String valorTexto = txtValorTotal.getText();
            String notaFiscal = txtNotaFiscal.getText();

            if (usuario.trim().isEmpty() || fornecedor.trim().isEmpty() || dataTexto.trim().isEmpty() || valorTexto.trim().isEmpty()) {
                exibirAvisoTemporario("Usuário, Fornecedor, Data e Valor são obrigatórios.", lbFormulario);
                return;
            }

            LocalDate dataCompra;
            try {
                dataCompra = LocalDate.parse(dataTexto, DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            } catch (DateTimeParseException e) {
                exibirAvisoTemporario("Formato de data inválido! Use dd/mm/aaaa.", lbFormulario);
                return;
            }

            Double valorTotal;
            try {
                valorTotal = Double.valueOf(valorTexto.replace(",", "."));
            } catch (NumberFormatException e) {
                exibirAvisoTemporario("Formato de valor inválido! Use apenas números.", lbFormulario);
                return;
            }

            if (!notaFiscal.trim().isEmpty() && !notaFiscal.matches("\\d+")) {
                exibirAvisoTemporario("A Nota Fiscal deve conter apenas números.", lbFormulario);
                return;
            }

            if (!notaFiscal.trim().isEmpty()) {
                Optional<Compra> compraExistente = compraRepository.findByNotaFiscal(notaFiscal);

                if (compraExistente.isPresent()
                        && (compraSelecionado == null || !compraExistente.get().getId().equals(compraSelecionado.getId()))) {
                    exibirAvisoTemporario("Já existe uma compra com este número de Nota Fiscal.", lbFormulario);
                    return;
                }
            }

            Compra compra;
            String mensagemSucesso;

            if (compraSelecionado != null && compraSelecionado.getId() != null) {
                compra = compraSelecionado;
                mensagemSucesso = "Compra alterada com sucesso!";
            } else {
                compra = new Compra();
                compra.setAtivo(true);
                mensagemSucesso = "Compra incluída com sucesso!";
            }

            compra.setUsuario(usuario);
            compra.setFornecedor(fornecedor);
            compra.setItens(itens);
            compra.setDataCompra(dataCompra);
            compra.setValorTotal(valorTotal);
            compra.setNumeroNotaFiscal(notaFiscal);

            compraRepository.saveOrUpdate(compra);

            JOptionPane.showMessageDialog(this, mensagemSucesso, "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            carregarTabelas();
            limparFormulario();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro ao salvar a compra: " + e.getMessage(), "Erro Inesperado", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_bntSalvarActionPerformed

    private void bntAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAlterarActionPerformed
        int selectedRow = tblAtivos.getSelectedRow();

        if (selectedRow != -1) {
            int modelRow = tblAtivos.convertRowIndexToModel(selectedRow);
            compraSelecionado = ativosTableModel.getCompraEm(modelRow);

            preencherFormulario(compraSelecionado);
        } else {
            exibirAvisoTemporario("Por favor, selecione uma compra na tabela para alterar.", lbAviso);
        }
    }//GEN-LAST:event_bntAlterarActionPerformed

    private void bntDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDeletarActionPerformed
        int selectedRow = tblAtivos.getSelectedRow();

        if (selectedRow == -1) {
            exibirAvisoTemporario("Por favor, selecione uma compra para mover para a lixeira.", lbAviso);
            return;
        }

        int response = JOptionPane.showConfirmDialog(
                this,
                "Tem certeza que deseja mover esta compra para a lixeira?",
                "Confirmar Exclusão",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            try {
                int modelRow = tblAtivos.convertRowIndexToModel(selectedRow);
                Compra compraParaDeletar = ativosTableModel.getCompraEm(modelRow);

                compraRepository.softDelete(compraParaDeletar.getId());

                JOptionPane.showMessageDialog(this, "Compra movida para a lixeira!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

                carregarTabelas();
                limparFormulario();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Ocorreu um erro ao excluir a compra: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_bntDeletarActionPerformed

    private void bntRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRestaurarActionPerformed
        int selectedRow = tblLixeira.getSelectedRow();

        if (selectedRow == -1) {
            exibirAvisoTemporario("Por favor, selecione uma compra na lixeira para restaurar.", lbAviso);
            return;
        }

        int response = JOptionPane.showConfirmDialog(
                this,
                "Deseja restaurar esta compra da lixeira?",
                "Confirmar Restauração",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            try {
                int modelRow = tblLixeira.convertRowIndexToModel(selectedRow);
                Compra compraParaRestaurar = lixeiraTableModel.getCompraEm(modelRow);

                compraRepository.restore(compraParaRestaurar.getId());

                JOptionPane.showMessageDialog(this, "Compra restaurada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

                carregarTabelas();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Ocorreu um erro ao restaurar a compra: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_bntRestaurarActionPerformed

    private void bntDeletarBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDeletarBancoActionPerformed
        int selectedRow = tblLixeira.getSelectedRow();

        if (selectedRow == -1) {
            exibirAvisoTemporario("Por favor, selecione uma compra na lixeira para excluir permanentemente.", lbAviso);
            return;
        }

        int response = JOptionPane.showConfirmDialog(
                this,
                "Esta ação é IRREVERSÍVEL e apagará a compra para sempre.\nTem certeza que deseja continuar?",
                "Exclusão Permanente",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            try {
                int modelRow = tblLixeira.convertRowIndexToModel(selectedRow);
                Compra compraParaExcluir = lixeiraTableModel.getCompraEm(modelRow);

                compraRepository.hardDelete(compraParaExcluir.getId());

                JOptionPane.showMessageDialog(this, "Compra excluída permanentemente!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

                carregarTabelas();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Ocorreu um erro ao excluir a compra do banco de dados: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_bntDeletarBancoActionPerformed

    private void btnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActionPerformed
        String nomeUsuarioBusca = txtUsuario.getText().trim();

        if (!nomeUsuarioBusca.isEmpty()) {
            try {
                List<Compra> resultados = compraRepository.findByUsuario(nomeUsuarioBusca);

                ativosTableModel.setCompras(resultados);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Ocorreu um erro ao buscar as compras: " + e.getMessage(), "Erro de Busca", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        } else {
            carregarTabelas();
        }
    }//GEN-LAST:event_btnBuscaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new exibirCompras().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAlterar;
    private javax.swing.JButton bntDeletar;
    private javax.swing.JButton bntDeletarBanco;
    private javax.swing.JButton bntRestaurar;
    private javax.swing.JButton bntSalvar;
    private javax.swing.JButton btnBusca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbAviso;
    private javax.swing.JLabel lbFormulario;
    private javax.swing.JTable tblAtivos;
    private javax.swing.JTable tblLixeira;
    private javax.swing.JTextField txtDataCompra;
    private javax.swing.JTextField txtFornecedor;
    private javax.swing.JTextField txtItens;
    private javax.swing.JTextField txtNotaFiscal;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
